export type ResourceAsset = {
  slug: string;
  title: string;
  description: string;
  audience: string;
  time: string;
  href: string;
  cta: string;
  tags: string[];
};

export const toolAssets: ResourceAsset[] = [
  {
    slug: "opsec-checklist",
    title: "OPSEC Checklist",
    description: "An interactive checklist to improve safer account, device, and exposure habits one step at a time.",
    audience: "For anyone starting from the basics.",
    time: "15-25 min",
    href: "/free-resources/opsec-checklist",
    cta: "Open checklist",
    tags: ["beginner", "accounts", "devices"],
  },
  {
    slug: "account-hardening-planner",
    title: "Account Hardening Planner",
    description: "A guided planner that turns your setup into a personalized hardening path.",
    audience: "For users who want practical next steps, not abstract advice.",
    time: "10-15 min",
    href: "/free-resources/account-hardening-planner",
    cta: "Plan your setup",
    tags: ["beginner", "accounts", "devices"],
  },
  {
    slug: "incident-triage",
    title: "Incident Triage",
    description: "A calm first-pass tool for suspicious logins, phishing scares, lost access, or device problems.",
    audience: "For users facing something urgent or confusing.",
    time: "5-10 min",
    href: "/free-resources/incident-triage",
    cta: "Start triage",
    tags: ["urgent", "accounts", "incident"],
  },
  {
    slug: "exposure-self-check",
    title: "Exposure Self-Check",
    description: "A guided self-assessment to spot account dependencies, identity overlap, and avoidable exposure.",
    audience: "For people who want a clearer sense of their risk.",
    time: "8-12 min",
    href: "/free-resources/exposure-self-check",
    cta: "Run self-check",
    tags: ["beginner", "urgent", "accounts", "crypto"],
  },
  {
    slug: "password-analyzer",
    title: "Password Strength Analyzer",
    description: "Check how strong your passwords really are. Client-side only, your password never leaves your browser.",
    audience: "For anyone who wants to understand password security.",
    time: "2-5 min",
    href: "/free-resources/password-analyzer",
    cta: "Analyze password",
    tags: ["beginner", "accounts"],
  },
  {
    slug: "phishing-quiz",
    title: "Phishing Detection Quiz",
    description: "Can you spot the difference between real messages and phishing attempts? Test yourself with 10 realistic scenarios.",
    audience: "For everyone. Phishing is the most common attack vector.",
    time: "5-10 min",
    href: "/free-resources/phishing-quiz",
    cta: "Take the quiz",
    tags: ["beginner", "incident"],
  },
  {
    slug: "device-hardening",
    title: "Device Hardening Checklist",
    description: "Step-by-step hardening guides for iPhone, Android, Mac, and Windows. Track your progress per device.",
    audience: "For people who want to lock down their devices properly.",
    time: "15-30 min",
    href: "/free-resources/device-hardening",
    cta: "Harden your device",
    tags: ["beginner", "devices"],
  },
  {
    slug: "breach-checker",
    title: "Breach Checker",
    description: "Check if your email has appeared in known data breaches. See which breaches, what was exposed, and what to do next.",
    audience: "For anyone who wants to know if their data has been leaked.",
    time: "1-2 min",
    href: "/free-resources/breach-checker",
    cta: "Check your email",
    tags: ["beginner", "accounts", "urgent"],
  },
  {
    slug: "security-score",
    title: "Security Score",
    description: "Take a 2-minute assessment and get a personalized security score from 0-100 with specific recommendations.",
    audience: "For anyone who wants a quick security health check.",
    time: "2-3 min",
    href: "/free-resources/security-score",
    cta: "Get your score",
    tags: ["beginner", "accounts", "devices"],
  },
  {
    slug: "phone-lookup",
    title: "Phone Exposure Checker",
    description: "Check how exposed your phone number is across caller ID databases, data brokers, and social platforms. Learn how to remove yourself.",
    audience: "For anyone concerned about phone number privacy.",
    time: "5-10 min",
    href: "/free-resources/phone-lookup",
    cta: "Check your number",
    tags: ["beginner", "privacy"],
  },
  {
    slug: "threat-model",
    title: "Threat Model Generator",
    description: "Answer a few questions about your profile and get a personalized threat model with prioritized action steps.",
    audience: "For users who want to understand their specific risk profile.",
    time: "3-5 min",
    href: "/free-resources/threat-model",
    cta: "Generate your model",
    tags: ["intermediate", "privacy"],
  },
  {
    slug: "account-mapper",
    title: "Account Dependency Mapper",
    description: "Map how your accounts are connected and see which ones are single points of failure. Visualize what happens if one is compromised.",
    audience: "For people who want to understand account dependencies.",
    time: "5-10 min",
    href: "/free-resources/account-mapper",
    cta: "Map your accounts",
    tags: ["intermediate", "accounts"],
  },
  {
    slug: "mfa-compare",
    title: "MFA Comparison Guide",
    description: "Compare SMS, authenticator apps, push notifications, and hardware keys side by side. Find the best MFA method for your needs.",
    audience: "For anyone setting up or upgrading two-factor authentication.",
    time: "3-5 min",
    href: "/free-resources/mfa-compare",
    cta: "Compare methods",
    tags: ["beginner", "accounts"],
  },
  {
    slug: "password-breach",
    title: "Password Breach Checker",
    description: "Check if your password has appeared in 700M+ breached passwords. Uses k-anonymity — your password never leaves your browser.",
    audience: "For anyone who wants to check if their passwords are compromised.",
    time: "1 min",
    href: "/free-resources/password-breach",
    cta: "Check password",
    tags: ["beginner", "accounts", "urgent"],
  },
  {
    slug: "dns-scanner",
    title: "Email Domain Security Scanner",
    description: "Scan any email domain for SPF, DMARC, DKIM, and MX records. Detect spoofing vulnerabilities automatically.",
    audience: "For anyone who wants to verify their email domain security.",
    time: "1-2 min",
    href: "/free-resources/dns-scanner",
    cta: "Scan domain",
    tags: ["intermediate", "accounts"],
  },
  {
    slug: "email-analyzer",
    title: "Email Header Analyzer",
    description: "Paste headers from a suspicious email to detect spoofing, trace the sender, and verify authentication. 100% client-side.",
    audience: "For anyone who received a suspicious email.",
    time: "2-5 min",
    href: "/free-resources/email-analyzer",
    cta: "Analyze headers",
    tags: ["intermediate", "incident"],
  },
  {
    slug: "username-osint",
    title: "Username OSINT Search",
    description: "Search a username across 30+ platforms automatically. See your digital footprint, find forgotten accounts, assess exposure.",
    audience: "For anyone who wants to understand their online presence.",
    time: "1-2 min",
    href: "/free-resources/username-osint",
    cta: "Search username",
    tags: ["beginner", "privacy"],
  },
  {
    slug: "website-scanner",
    title: "Website Security Scanner",
    description: "Scan any website for security headers, HTTPS, and common vulnerabilities. Get a letter grade with fix recommendations.",
    audience: "For anyone who wants to check if a website is secure.",
    time: "1-2 min",
    href: "/free-resources/website-scanner",
    cta: "Scan website",
    tags: ["intermediate", "devices"],
  },
];

export const guideHighlights: ResourceAsset[] = [
  {
    slug: "digital-privacy-everyday-people",
    title: "Digital Privacy for Everyday People",
    description: "A grounded introduction to better digital habits without becoming paranoid.",
    audience: "For normal users who want a practical starting point.",
    time: "8 min read",
    href: "/guides/digital-privacy-everyday-people",
    cta: "Read guide",
    tags: ["beginner", "privacy"],
  },
  {
    slug: "gmail-hardening-checklist",
    title: "A Practical Gmail Hardening Checklist",
    description: "The key Gmail settings and habits that matter most for normal users.",
    audience: "For Gmail users who want safer defaults.",
    time: "7 min read",
    href: "/guides/gmail-hardening-checklist",
    cta: "Read guide",
    tags: ["accounts", "beginner"],
  },
  {
    slug: "recovery-and-mfa-guide",
    title: "Recovery & MFA Setup Guide",
    description: "How to harden account recovery without locking yourself out later.",
    audience: "For anyone cleaning up account recovery and MFA.",
    time: "9 min read",
    href: "/guides/recovery-and-mfa-guide",
    cta: "Read guide",
    tags: ["accounts", "intermediate"],
  },
  {
    slug: "crypto-opsec-basics",
    title: "Crypto OPSEC Basics",
    description: "Simple habits for users who hold crypto and want fewer avoidable mistakes.",
    audience: "For crypto users who want a safer baseline.",
    time: "7 min read",
    href: "/guides/crypto-opsec-basics",
    cta: "Read guide",
    tags: ["crypto", "beginner"],
  },
];

export const templateAssets: ResourceAsset[] = [
  {
    slug: "account-inventory-template",
    title: "Account Inventory Template",
    description: "A starter structure for mapping your important accounts, recovery options, and owners.",
    audience: "For anyone trying to understand what they already have.",
    time: "10 min setup",
    href: "/open-resources#account-inventory-template",
    cta: "Open template",
    tags: ["beginner", "accounts", "template"],
  },
  {
    slug: "remediation-plan-template",
    title: "30-Day Remediation Plan",
    description: "A lightweight template for spacing out account cleanup over a month.",
    audience: "For people who want to improve without doing everything in one day.",
    time: "5 min setup",
    href: "/open-resources#remediation-plan-template",
    cta: "View plan",
    tags: ["beginner", "template"],
  },
  {
    slug: "incident-response-checklist",
    title: "Incident Response Checklist",
    description: "A simple checklist to keep your first response calm and structured.",
    audience: "For users who want something ready before a scare happens.",
    time: "5 min setup",
    href: "/open-resources#incident-response-checklist",
    cta: "View checklist",
    tags: ["urgent", "template", "incident"],
  },
  {
    slug: "digital-footprint-map",
    title: "Digital Footprint Map",
    description: "A basic map for seeing where your identities, handles, and accounts overlap.",
    audience: "For people who want to reduce unnecessary exposure.",
    time: "10 min setup",
    href: "/open-resources#digital-footprint-map",
    cta: "Open map",
    tags: ["privacy", "template"],
  },
];

export type OpenRepo = {
  slug: string;
  name: string;
  audience: string;
  description: string;
  cta: string;
  href: string;
  license: string;
};

export const openRepos: OpenRepo[] = [
  {
    slug: "opsec-checklists",
    name: "opsec-checklists",
    audience: "Beginner to intermediate users",
    description: "Markdown checklists and simple walkthroughs for safer online habits.",
    cta: "View repo",
    href: "https://github.com/fk94security/opsec-checklists",
    license: "MIT",
  },
  {
    slug: "account-hardening-guides",
    name: "account-hardening-guides",
    audience: "People cleaning up email, recovery, and MFA",
    description: "Practical hardening guides for common account setups and recovery paths.",
    cta: "View repo",
    href: "https://github.com/fk94security/account-hardening-guides",
    license: "CC BY 4.0",
  },
  {
    slug: "security-templates",
    name: "security-templates",
    audience: "People who need structure, not theory",
    description: "Reusable templates for account inventories, remediation plans, and incident checklists.",
    cta: "View repo",
    href: "https://github.com/fk94security/security-templates",
    license: "MIT",
  },
  {
    slug: "privacy-starter-pack",
    name: "privacy-starter-pack",
    audience: "People getting started with digital privacy",
    description: "A curated starter pack with beginner-friendly privacy resources and setup notes.",
    cta: "View repo",
    href: "https://github.com/fk94security/privacy-starter-pack",
    license: "CC BY 4.0",
  },
  {
    slug: "fk94-guides",
    name: "fk94-guides",
    audience: "Readers who want all guides in one place",
    description: "An index of FK94 writing, updates, and open resources with cross-links to the site.",
    cta: "View repo",
    href: "https://github.com/fk94security/fk94-guides",
    license: "MIT",
  },
];
